name: Go CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Instalar dependências
        run: go mod tidy

      - name: Rodar testes
        run: go test ./... -v -race -count=1
        env:
          JWT_SECRET: ci_test_secret_only